label: click
protected_feature: protected_attribute
protected_feature_for_model: protected_attribute_feat
categorical_id_features:
- user_id
- impression_id
- product_id
categorical_features:
- cat0
- cat1
- cat2
- cat3
- cat4
- cat5
- cat6
- cat7
- cat8
- cat9
- cat10
- cat11
- cat12
binary_context_features:
- senior
- displayrandom
numeric_features:
- rank
- num16
- num17
- num18
- num19
- num20
- num21
- num22
- num23
- num24
- num25
- num26
- num27
- num28
- num29
- num30
- num31
- num32
- num33
- num34
- num35
- num36
- num37
- num38
- num39
- num40
- num41
- num42
- num43
- num44
- num45
- num46
- num47
- num48
- num49
- num50
unaware_features:
- user_id
- impression_id
- product_id
- cat0
- cat1
- cat2
- cat3
- cat4
- cat5
- cat6
- cat7
- cat8
- cat9
- cat10
- cat11
- cat12
- senior
- displayrandom
- rank
- num16
- num17
- num18
- num19
- num20
- num21
- num22
- num23
- num24
- num25
- num26
- num27
- num28
- num29
- num30
- num31
- num32
- num33
- num34
- num35
- num36
- num37
- num38
- num39
- num40
- num41
- num42
- num43
- num44
- num45
- num46
- num47
- num48
- num49
- num50
unfair_features:
- user_id
- impression_id
- product_id
- cat0
- cat1
- cat2
- cat3
- cat4
- cat5
- cat6
- cat7
- cat8
- cat9
- cat10
- cat11
- cat12
- senior
- displayrandom
- rank
- num16
- num17
- num18
- num19
- num20
- num21
- num22
- num23
- num24
- num25
- num26
- num27
- num28
- num29
- num30
- num31
- num32
- num33
- num34
- num35
- num36
- num37
- num38
- num39
- num40
- num41
- num42
- num43
- num44
- num45
- num46
- num47
- num48
- num49
- num50
- protected_attribute_feat
